### PR TITLE
feat(api): add api/v1/og route for OG Image; feat(website): update head to use og image content

### PR DESCRIPTION
**Pull request by chukwumaokere**
To resolve: https://github.com/chronark/envshare/issues/22
Testable at: http://localhost:3000/api/v1/og
or 
http://localhost:3000/api/v1/og?title=Some%20Random%20Title&subtitle=EnvShare2

This PR is still a work in progress because I'm finding issues with tailwind styles on OG Image routes 
It works in their [playground](https://og-playground.vercel.app/?share=dVJLbsIwEL2KNRs2sRKgLWqUsuMEVN1AF_k4ialjR86EJEXcveMEEKjtxp4ZPb2PPSdITSYghCiTR4bd26zju_kiCOr-k5V897JYuSpXoh8PnhrFJIqq4anQKCw7tA3KfLi2KHq81LP1XjN2Jd5DUvBExekXo6KwcSYJxdFwtCy3puLfUqf8NQj854DReGxX1C4D1vG8VYoMjZczsoeR_Z7_0eRoZNkT2pBMYlTG0JK61AVHWZQ4IcjIwJfBTeIh20Xv_4g3F-SjqWM9GRkBJKZpZAn3K7AbpErW3CHvws9v4buSjExKq_sMJLgtiZRt9FFaoytHHyXWX7OP2Mo4UaJhW5G2Vqgh8p2nvxxWyJ-IikhGtgdg5NOLTl93qaYbPDA1SqMbCE_QyQxLCN2qeFAK96AQ0rZ4kImkLSDMY9UID0RlDvJ9qN2OYTd2ROTybKpEZBCibcX5_AM)
image

```bash
wait  - compiling /api/v1/og (client and server)...
event - compiled successfully in 246 ms (67 modules)
`gradient-to-tr` unknown or invalid utility
`from-zinc-900/50` unknown or invalid utility
`to-zinc-700/30` unknown or invalid utility
`gradient-to-t` unknown or invalid utility
`clip-text` unknown or invalid utility
`from-zinc-100/50` unknown or invalid utility
`to-white` unknown or invalid utility
`whitespace-pre` unknown or invalid utility
```

Researching here: https://github.com/jaredh159/tailwind-react-native-classnames/issues/121 and https://github.com/vercel/og-image/issues/226#issuecomment-1345147106

And also need a suggestion for head component fetching hostname
In next 12 it was something with `getServerSideProps` -> `req.hostname` or something like that
And in next13 theres probably a different way to do it. 
We cant use `window.location.href` to build the URL because window can be undefined which would probably result in some OG Image issues. 
I'll check on this also

### CODE REVIEW

**Comment by chukwumaokere** [comment]
"Window can be undefined when static generated, however it will be updated when the page is hydrated"... 
🤔 
I wonder what that means for the OG Image embed then..

**Comment by chronark** [comment]
`const host = new URL(req.url).hostname` should work

**Comment by chukwumaokere** [comment]
Originally I did have it as: `const url = new URL(`${window.location.href}api/v1/og?title=${encodeURIComponent(title)}`);`

image

I changed it back to think it over a bit more 

And after some research I see im [not the only one](https://www.reddit.com/r/nextjs/comments/yef3xc/nextjs_13_how_do_you_access_the_request_object/) with this issue so theres: https://beta.nextjs.org/docs/api-reference/headers#headers

**Comment by chronark** [comment]
ah you're inside a `page.tsx`, I'm not sure tbh, if we don't find anything I'll ask vercel

**Comment by chukwumaokere** [comment]
> const host = new URL(req.url).hostname

Not in the endpoint, in the app/head.tsx implementation that makes a request to the API 

Originally I did have it as: `const url = new URL(`${window.location.href}api/v1/og?title=${encodeURIComponent(title)}`);`

image

I changed it back to think it over a bit more 

And after some research I see im [not the only one](https://www.reddit.com/r/nextjs/comments/yef3xc/nextjs_13_how_do_you_access_the_request_object/) with this issue so theres: https://beta.nextjs.org/docs/api-reference/headers#headers 

I have a feeling I did something incorrectly 🤨

**Comment by chronark** [comment]
aah ok I see now, I think using the host from headers is fine

**Comment by chukwumaokere** [comment]
Sounds good. Though, it might break if someone clones repo and hosts elsewhere though, but thats not for us to worry about LOL 

It can be in the documentation that there are components like Head that expect this to be hosted on vercel, and if they're choosing to selfhost, they'll want to change this files environment variable to use their BASE_URL or whatever their environment variable name for host is

**Comment by chronark** [comment]
Yeah I had the same thoughts, maybe we can do use `VERCEL_URL` and if that is not available, then we fall back to the host in headers.
But let's worry about that later

**Comment by chukwumaokere** [comment]
I address this in the documentation

image

**Comment by chukwumaokere** [comment]
FYI the only issue i'm fixing now from this PR is the tailwind issue that is making the tailwind styles not work 
Once thats done, the PR is ready I'll look into it more later today, gotta get back to my day job haha
```bash
wait  - compiling /api/v1/og (client and server)...
event - compiled successfully in 246 ms (67 modules)
`gradient-to-tr` unknown or invalid utility
`from-zinc-900/50` unknown or invalid utility
`to-zinc-700/30` unknown or invalid utility
`gradient-to-t` unknown or invalid utility
`clip-text` unknown or invalid utility
`from-zinc-100/50` unknown or invalid utility
`to-white` unknown or invalid utility
`whitespace-pre` unknown or invalid utility
```

**Comment by chronark** [comment]
Let's just do it without the gradient, then you can remove all of those I think

**Comment by chukwumaokere** [comment]
Fair enough, I'll remove them for now, we'll have a bit of an MVP and then modify it later

**Comment by chronark** [comment]
👍 
Can you remove the draft status and then I'll merge

**Comment by chukwumaokere** [comment]
image

Had to inline style the tailwind 
```jsx
<div tw='w-[1200px] h-[630px] flex flex-col items-center justify-center text-center'>
                {/* backgroundImage: bg-gradient-to-tr from-zinc-900/50 to-zinc-700/30 */}
                <div tw="bg-black w-full h-full flex" style={{backgroundImage: 'linear-gradient(to top right, rgba(24,24,27,.5), rgba(63,63,70,.3))'}}>
                    <div tw="flex flex-col text-3xl tracking-tight text-gray-300 w-full items-center h-full justify-center text-center">
                        {/* font-semibold bg-gradient-to-t bg-clip-text from-zinc-100/50 to-white whitespace-pre */ }
                        <span tw="text-white text-7xl" 
                            style={{fontWeight: 700, 
                                color: 'transparent',
                                paddingLeft: '12rem',
                                paddingRight: '12rem',
                                backgroundImage: 'linear-gradient(to top, rgba(244, 244,  245, .5), rgba(255,255,255,1))', 
                                backgroundClip: 'text'}}>{title}</span>
                        <span tw="mt-4 font-bold">{subtitle}</span>
                    </div>
                </div>
            </div>
```
I'll figure out at another point WHY this doesnt work and fix it later

**Pull request merged**
